tensorflow/swift

Usage.md
Add link to FAQ about optimization flag and add -O flag to Ubuntu's command.
=> Update Usage.md with optimization flag.

docs/AggregateParameters.md
Dear contributors, please approve my commit with minor changes in documentation. 
ParameterAggregate -> ParameterGroup.
=> Rename ParameterAggregate to ParameterGroup (#19791) in documentation.

docs/DesignOverview.md
For static single assignment (SSA) since this wasn't the easiest term to google for in this context.
=> Add link for SSA

docs/site/_book.yaml
Updates book to reflect new structure
=> Update devsite book yaml

Installation.md
Adding  links to specific releases.
=> Adding installation instructions for release versions. 

docs/site/_book.yaml
`/install/toc.yaml` -> `/install/_toc.yaml`
=> Fix `_book.yaml` link.

README.md
=> Add tutorials to README.

docs/ParameterOptimization.md
@lattner pointed out that this could be made more clear. Updated to:
> Machine learning models are concepturally functions with internal state called "parameters". In code, models are often represented as a data structure that stores parameters as mutable properties and has an "apply" method.
=> Reword "models are data structures ..."

docs/site/tutorials/a_swift_tour.ipynb
The old version was outdated and had formatting errors.
- Update tutorial to match current contents of
https://docs.swift.org/swift-book/GuidedTour/GuidedTour.html.
- Change "Experiment" sections to be code cells rather than text.
Notebook viewers can enter code and experiment.
View the tutorial here: https://github.com/tensorflow/swift/blob/tutorials/docs/site/tutorials/a_swift_tour.ipynb
=> Fix "A Swift Tour" tutorial.

docs/DifferentiableFunctions.md
Follow-up to https://github.com/apple/swift/pull/23139.
Addresses #161.
=> Fix derivative of `squareRoot` in document.

docs/site/tutorials/python_interoperability.ipynb
This resolves https://bugs.swift.org/browse/TF-397
https://nbviewer.jupyter.org/github/realdoug/tensorflow-swift/blob/TF-397/docs/site/tutorials/python_interoperability.ipynb?invalidatecache=somethingunique
=> [TF-397] add documentation for setting python version

Installation.md
=> Correcting minor installation doc mistake

docs/DifferentiableFunctions.md, docs/DifferentiableTypes.md, docs/ParameterOptimization.md
Replaced instances of `applied(to:)` to `call(_:)`.
=> Updated technical documents to use the new Layer protocol.

README.md
These two lines seemingly don't work.
=> Fix README's numpy example

Installation.md
Relevant thread:
https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/cf-oGS0_wBw
=> New macOS toolchains require Xcode 11

Installation.md
https://github.com/apple/swift/commit/2761ac9f8700f8c21c71f1a15733af44bd42f333
Also removed trailing whitespace.
=> Add installation links to v0.4-rc2 toolchains.

Usage.md
These modifications are based on the suggestions by Dave Fernandes here: https://groups.google.com/a/tensorflow.org/d/msg/swift/YntTUh6E20Q/LchmSQhIBAAJ
=> Updated Xcode project setup instructions.

Installation.md
https://github.com/apple/swift/commit/7d157f346b4424d3acb2e8e4c08ac9970d42f1bf
=> Add installation links to v0.4-rc4 toolchains.

Installation.md
https://github.com/apple/swift/commit/3416770d7303ea763de228895983219fcbab35ad
=> Release 2019-07-25 toolchain for macOS.

README.md
Add tutorial from #187. Thank you @bartchr808!
=> [README] Add protocol-oriented programming & generics tutorial.

.gitignore, .swift-format, Package.swift, Sources/SIL/Bitcode.swift, Sources/SIL/BitcodeParser.swift, Sources/SIL/BitcodePrinter.swift, Sources/SIL/Bitstream.swift, Sources/SIL/Parser.swift, Sources/SIL/Printer.swift, Sources/SIL/SIL.swift, Sources/SIL/SILParser.swift, Sources/SIL/SILPrinter.swift, Tests/SILTests/BitcodeTests.swift, Tests/SILTests/BitstreamTests.swift, Tests/SILTests/DescriptionTests.swift, Tests/SILTests/InstructionTests.swift, Tests/SILTests/ModuleTests.swift, Tests/SILTests/PrinterTests.swift, Tests/SILTests/Process.swift, Tests/SILTests/Resources/AddFloat.swift, Tests/SILTests/Resources/AvgPool1D.swift, Tests/SILTests/TemporaryFile.swift, docs/site/tutorials/TutorialDatasetCSVAPI.swift
This is something that @apaszke-g and I have hacked up last week.
This is an alternative and complementary approach to metaprogramming Swift with quasiquotes (https://github.com/tensorflow/swift/pull/225). It will be interesting to explore both.
=> Data model and parser for SIL

Sources/SIL/SIL.swift, Sources/SIL/SILParser.swift, Sources/SIL/SILPrinter.swift
Might be a good idea to land without squashing, because they're all independent.
cc @burmako
=> Assorted improvements to libSIL

Installation.md
This PR just adds links to the v0.5-rc0.
=> Add links to v0.5-rc0 

Installation.md
https://github.com/apple/swift/commit/28ce7af28dfc9e98d630f39f42f18fcccb98268c
=> Release 2019-11-04 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/4d1c1df58f9aeb0bc2bdba0b6723d1646fb0ddab
=> Release 2019-11-07 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/e242a8825fbbb74260ced075002e13840342faae
=> Release 2019-11-11 toolchain for macOS.

Installation.md, Usage.md
Add a note to help first-time users who encounter REPL crashes like
https://bugs.swift.org/browse/TF-940.
=> Add installation verification steps

Installation.md
https://github.com/apple/swift/commit/04dca63ecfd37d9c871cc60832290e204fe96255
=> Release 2019-11-15 toolchain for macOS.

docs/site/tutorials/protocol_oriented_generics.ipynb
Just a few suggestions:
- Minor grammar and syntax changes to be more in line with the Google/TF style guides
- Fixing the bullet points at the end of the notebook
For some reason, it says "1,166 additions and 1,200 deletions" after performing the edits in Colab.
Feel free to make amendments, propose suggestions, etc. Thanks!
=> Minor edits: Swift notebook on Protocol-oriented programming & generics

Installation.md
https://github.com/apple/swift/commit/49e88356ca52859b821ab147d4418df9633aed87
---
Notable change: `swift-DEVELOPMENT-SNAPSHOT-2019-11-20-a -> tensorflow` merge.
=> Release 2019-12-03 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/74515825246539666a5f716cbb284350ad76a7a3
---
Notable change: `swift-DEVELOPMENT-SNAPSHOT-2019-12-09-a -> tensorflow` merge.
=> Release 2019-12-12 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/05c45392d5f063947d4f6df0e2335186cdd82f7e
---
- `swift-DEVELOPMENT-SNAPSHOT-2019-12-16-a -> tensorflow` merge: https://github.com/apple/swift/pull/28847.
- Array literal differentiation fixes: https://github.com/apple/swift/pull/28889.
=> Release 2019-12-19 toolchain for macOS.

docs/AutomaticDifferentiation.md, docs/GraphProgramExtraction.md
`dlvm.org` -> `dlvm-team.github.io`
=> Fix DLVM links.

README.md
=> Update "last updated" date for ∂P manifesto.

Tests/QuoteTests/CompilationTests.swift, Tests/QuoteTests/DescriptionTests.swift, Tests/QuoteTests/StructureTests.swift
This takes care of the breakage discovered by Rapid.
=> Merge tag 'swift-DEVELOPMENT-SNAPSHOT-2020-01-20-a' into tensorflow

Installation.md
https://github.com/apple/swift/commit/e40d33e35374fa997985f3095fda295396a17a90
---
- `swift-DEVELOPMENT-SNAPSHOT-2020-01-31-a -> tensorflow` merge.
- `swift-jupyter` code completion fixes.
- Class differentiation: `@differentiable` class initializers and `ref_element_addr`/`unchecked_ref_cast`/`upcast` differentiation support.
=> Release 2020-02-11 toolchain for macOS.

docs/site/tutorials/model_training_walkthrough.ipynb, docs/site/tutorials/python_interoperability.ipynb
As discussed at the last meeting, adding language to explicitely mark the lines of code only working in Jupyter Notebook
=> Document cells specific to Jupyter Notebook

Installation.md
https://github.com/apple/swift/commit/5f62183f3c7772fa26b81a05b234f572d4ba9003
=> Release 2020-02-12 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/c076da970288c590f933d8834342214d9c6d8ffa
---
Notable changes: recent `master -> tensorflow` merge (2020-02-11).
=> Release 2020-02-19 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/01f6a9227d30395a53af5a8d7e355f5e36090cef
---
Notable change: `swift-DEVELOPMENT-SNAPSHOT-2020-03-19-a -> tensorflow` merge.
=> Release 2020-03-20 toolchain for macOS.

Installation.md
As discussed in #411 
- Fixed Win version in Requirements, added footnote on how to check current version
- Placed footnotes at the end of Windows section
- Sentence case and minor punctuation
=> Update Windows docs

Installation.md
https://github.com/apple/swift/commit/33d11922ecd57facb125e663818e5a674970b08c
---
Notable change: `swift-DEVELOPMENT-SNAPSHOT-2020-03-24-a -> tensorflow` merge.
=> Release 2020-03-25 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/aa81f942c69755fe60d4f3a9e7dd47d85a62c294
---
Notable change: `swift-DEVELOPMENT-SNAPSHOT-2020-04-06-a -> tensorflow` merge.
=> Release 2020-04-07 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/039d371753a6d864b2057bb7953b79147ae6e6be
---
Notable changes
- `swift-DEVELOPMENT-SNAPSHOT-2020-04-13-a -> tensorflow` merge.
- SwiftPM patch applied to fix `swift test --filter ...`: https://github.com/apple/swift-package-manager/pull/2692.
=> Release 2020-04-15 toolchain for macOS.

Installation.md
The immediate mode issue is still there and will have to wait for next release.
=> Releasing 0.9 for MacOS

Installation.md
https://github.com/apple/swift/commit/112f6d30ba69857fea2115e9836a55c89b355f20
---
Notable change: differentiation fixes in https://github.com/apple/swift/pull/32033.
=> Release 2020-05-26 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/91d4726b3d600f3a5fbcfc9911daa63b1cd88b02
https://github.com/tensorflow/swift-apis/commit/15435771466749d96857bc508efa646060b31d94
=> Release 2020-06-03 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/09c12c9a39a753725ed8bd7701c4bb1e149b0d45
https://github.com/tensorflow/swift-apis/commit/c65f83439f29adb508c06c4fbd023290b58da4f2
=> Release 2020-06-08 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/97957b4434bb1fb2aadadc28011e30db1cdd32fa
https://github.com/tensorflow/swift-apis/commit/e9df616445bad8e66b48ae47674dacbc34949466
---
Notable change: `swift-DEVELOPMENT-SNAPSHOT-2020-06-08-a -> tensorflow` merge.
=> Release 2020-06-09 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/f2b25f73556ec379d9482cd9ce93f80badbf658b
https://github.com/tensorflow/swift-apis/commit/2500de10cfa2ecc9a8427dfb0a0d789aa9cdb83e
---
Notable change: `2020-06-14 -> tensorflow` merge.
=> Release 2020-06-17 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/cb0b03bff6078b6b6f548723c65a207337f2bc59
https://github.com/tensorflow/swift-apis/commit/215c1380874c55d2f12ae81ce78968f9e25ed723
---
Notable change: [`2020-06-22 -> tensorflow` merge](https://github.com/apple/swift/pull/32512).
=> Release 2020-06-25 toolchain for macOS.

docs/site/tutorials/model_training_walkthrough.ipynb
Dan Hurt found that the ReLU link was not pointing to the correct place.
=> Update the ReLU Link

Installation.md
https://github.com/apple/swift/commit/2c4485873fec6a931bec4e2ef5b4305793ef62b3
https://github.com/tensorflow/swift-apis/commit/83f02321f91cd89c5e71c98c29f9cc296d9bc30f
---
Notable change: [`2020-07-07 -> tensorflow` merge](https://github.com/apple/swift/pull/32760).
=> Release 2020-07-11 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/3c6fe132533201fec6ab485f78d45fc807142c3e
https://github.com/tensorflow/swift-apis/commit/bf942f2634862596a01f8fe5a5a049ecd3b6f2a4
---
Notable change: [`2020-07-14 -> tensorflow` merge](https://github.com/apple/swift/pull/32882).
=> Release 2020-07-16 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/538d62b9b5d36dc2226df0f7525d1cd44651043e
https://github.com/tensorflow/swift-apis/commit/7a28ba3304e13edf729ae8036683a5a66ddb013f
---
Notable change: [`2020-07-28 -> tensorflow` merge](https://github.com/apple/swift/pull/33160).
=> Release 2020-07-29 toolchain for macOS.

Installation.md
https://github.com/apple/swift/commit/dc868d4147476ffafc3bc8797664aebf56fe7c38
https://github.com/tensorflow/swift-apis/commit/f7cb1aa1ec222a8bb639b298255b4a59669e4fb7
=> Release 2020-08-05 toolchain for macOS.

Installation.md
Update with new MacOS dev build and update to use xcode 12
=> Update with new MacOS dev build and update to use xcode 12

Installation.md
Releasing 0.11
Also small change to make development build names consistent with release build names.
=> Releasing 0.11

docs/site/tutorials/introducing_x10.ipynb
Not sure if you'd want this change on master as well.
=> fix import branch

Installation.md
https://github.com/apple/swift/commit/48350ecca3852130620bd87f7bd2877f847cd175
https://github.com/tensorflow/swift-apis/commit/897bac90dab6d70586c8697b08eb8d72d68d4253
=> Release 2020-08-26 toolchain for macOS.

docs/ParameterOptimization.md
=> [docs] note ParameterOptimization is out of date

Installation.md
https://github.com/apple/swift/commit/c08d0804e2e44acba1c86937f738114a0ba6b0e4
https://github.com/tensorflow/swift-apis/commit/b719d997beca0f6ddb8576776ee917556cfc485c
---
Notable changes since last toolchain: various autodiff fixes (https://github.com/apple/swift/pull/33868, https://github.com/apple/swift/pull/33897, https://github.com/apple/swift/pull/33969).
=> Release 2020-09-16 toolchain for macOS.

utils/install-ubuntu1804-test.sh, utils/install-ubuntu1804.sh
Trying to fix some documentation build issues by removing a potentially conflicting Python installation. Using a forked install script to verify first.
=> Forking install script to fix documentation updates
